schema_version: 1

context:
  version: 1.6.2

package:
  name: python-discovery
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-discovery/python_discovery-${{ version }}.tar.gz
  sha256: cd1738ca1d37c86ef9d0b654dd46fcee1e41c97c6add12575e8501ced39afdb4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch-vcs >=0.5
    - hatchling >=1.28
    - pip
  run:
    - python >=${{ python_min }}
    - filelock >=3.16.1
tests:
  - python:
      imports:
        - python_discovery
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: Python interpreter discovery
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tox-dev/python-discovery
  repository: https://github.com/tox-dev/python-discovery
  documentation: https://python-discovery.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
